[package]
name = "breakout-rust"
version = "0.1.0"
authors = ["Sandra <sandra.traven@gmail.com> Björn <benglesson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
